{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nextjs-app-secrets
  labels:
    app: nextjs-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.serviceAccount.azureClientId | quote }}
    keyvaultName: {{ .Values.secretProvider.keyvaultName | quote }}
    tenantId: {{ .Values.secretProvider.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: demo-api-key
          objectType: secret
{{- end }}