{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextjs-app
  labels:
    app: nextjs-app
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azureClientId | quote }}
{{- end }}